package io.github.jared.xlowerseek;
import org.junit.Test;import static org.junit.Assert.*;import java.io.*;import java.nio.file.*;import java.util.concurrent.atomic.AtomicBoolean;import java.util.zip.*;import java.security.*;
public class ModelBundleTest {
 private File zip(String name,String text)throws Exception{File f=File.createTempFile("bundle",".zip");f.deleteOnExit();try(ZipOutputStream out=new ZipOutputStream(new FileOutputStream(f))){out.putNextEntry(new ZipEntry(name));out.write(text.getBytes(java.nio.charset.StandardCharsets.UTF_8));out.closeEntry();}return f;}
 private String hash(String text)throws Exception{StringBuilder b=new StringBuilder();for(byte v:MessageDigest.getInstance("SHA-256").digest(text.getBytes(java.nio.charset.StandardCharsets.UTF_8)))b.append(String.format("%02x",v&255));return b.toString();}
 private ModelBundle.Entry[] entries()throws Exception{return new ModelBundle.Entry[]{new ModelBundle.Entry("en/model.bin",4,hash("data"))};}
 @Test public void publishesOnlyValidatedFile()throws Exception{File root=Files.createTempDirectory("model").toFile();ModelBundle.install(zip("en/model.bin","data"),root,entries(),new AtomicBoolean());assertEquals("data",new String(Files.readAllBytes(new File(root,"en/model.bin").toPath()),java.nio.charset.StandardCharsets.UTF_8));}
 @Test public void rejectsTraversal()throws Exception{try{ModelBundle.install(zip("../escape","data"),Files.createTempDirectory("model").toFile(),entries(),new AtomicBoolean());fail();}catch(IOException expected){}}
 @Test public void corruptReplacementPreservesPreviousFile()throws Exception{File root=Files.createTempDirectory("model").toFile();new File(root,"en").mkdirs();File target=new File(root,"en/model.bin");Files.write(target.toPath(),"data".getBytes(java.nio.charset.StandardCharsets.UTF_8));try{ModelBundle.install(zip("en/model.bin","xxxx"),root,entries(),new AtomicBoolean());fail();}catch(IOException expected){}assertEquals("data",new String(Files.readAllBytes(target.toPath()),java.nio.charset.StandardCharsets.UTF_8));assertFalse(new File(target+".installing").exists());}
 @Test public void rejectsOversizedEntry()throws Exception{try{ModelBundle.install(zip("en/model.bin","data-too-long"),Files.createTempDirectory("model").toFile(),entries(),new AtomicBoolean());fail();}catch(IOException expected){}}
 @Test public void cancellationLeavesNoPublishedModel()throws Exception{File root=Files.createTempDirectory("model").toFile();try{ModelBundle.install(zip("en/model.bin","data"),root,entries(),new AtomicBoolean(true));fail();}catch(ModelTransfer.Paused expected){}assertFalse(new File(root,"en/model.bin").exists());}
}
